CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FullName NVARCHAR(120) NOT NULL,
  Email NVARCHAR(120) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE Roles (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(80) NOT NULL UNIQUE);
CREATE TABLE Permissions (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(120) NOT NULL UNIQUE);
CREATE TABLE UserRoles (Id INT IDENTITY(1,1) PRIMARY KEY, UserId INT NOT NULL, RoleId INT NOT NULL, FOREIGN KEY (UserId) REFERENCES Users(Id), FOREIGN KEY (RoleId) REFERENCES Roles(Id));
CREATE TABLE RolePermissions (Id INT IDENTITY(1,1) PRIMARY KEY, RoleId INT NOT NULL, PermissionId INT NOT NULL, FOREIGN KEY (RoleId) REFERENCES Roles(Id), FOREIGN KEY (PermissionId) REFERENCES Permissions(Id));
CREATE TABLE Categories (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(120) NOT NULL, Description NVARCHAR(300));
CREATE TABLE Suppliers (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(120) NOT NULL, Email NVARCHAR(120), Phone NVARCHAR(40), Address NVARCHAR(255));
CREATE TABLE Warehouses (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(120) NOT NULL, Location NVARCHAR(255));
CREATE TABLE Products (Id INT IDENTITY(1,1) PRIMARY KEY, CategoryId INT, Name NVARCHAR(120) NOT NULL, SKU NVARCHAR(80) NOT NULL UNIQUE, UnitPrice DECIMAL(18,2) NOT NULL, ReorderLevel INT NOT NULL DEFAULT 0, FOREIGN KEY (CategoryId) REFERENCES Categories(Id));
CREATE TABLE Inventory (Id INT IDENTITY(1,1) PRIMARY KEY, WarehouseId INT NOT NULL, ProductId INT NOT NULL, Quantity INT NOT NULL DEFAULT 0, FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id), FOREIGN KEY (ProductId) REFERENCES Products(Id));
CREATE TABLE InventoryTransactions (Id INT IDENTITY(1,1) PRIMARY KEY, WarehouseId INT NOT NULL, ProductId INT NOT NULL, Quantity INT NOT NULL, TransactionType NVARCHAR(20) NOT NULL, ReferenceType NVARCHAR(40), ReferenceId INT, CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(), FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id), FOREIGN KEY (ProductId) REFERENCES Products(Id));
CREATE TABLE PurchaseOrders (Id INT IDENTITY(1,1) PRIMARY KEY, SupplierId INT NOT NULL, WarehouseId INT NOT NULL, OrderDate DATE NOT NULL, Status NVARCHAR(30) NOT NULL, FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id), FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id));
CREATE TABLE PurchaseOrderDetails (Id INT IDENTITY(1,1) PRIMARY KEY, PurchaseOrderId INT NOT NULL, ProductId INT NOT NULL, Quantity INT NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL, FOREIGN KEY (PurchaseOrderId) REFERENCES PurchaseOrders(Id), FOREIGN KEY (ProductId) REFERENCES Products(Id));
CREATE TABLE Customers (Id INT IDENTITY(1,1) PRIMARY KEY, FullName NVARCHAR(120) NOT NULL, Email NVARCHAR(120), Phone NVARCHAR(40), Address NVARCHAR(255));
CREATE TABLE SalesOrders (Id INT IDENTITY(1,1) PRIMARY KEY, CustomerId INT NOT NULL, WarehouseId INT NOT NULL, OrderDate DATE NOT NULL, Status NVARCHAR(30) NOT NULL, FOREIGN KEY (CustomerId) REFERENCES Customers(Id), FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id));
CREATE TABLE SalesOrderDetails (Id INT IDENTITY(1,1) PRIMARY KEY, SalesOrderId INT NOT NULL, ProductId INT NOT NULL, Quantity INT NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL, FOREIGN KEY (SalesOrderId) REFERENCES SalesOrders(Id), FOREIGN KEY (ProductId) REFERENCES Products(Id));
CREATE TABLE Deliveries (Id INT IDENTITY(1,1) PRIMARY KEY, SalesOrderId INT NOT NULL, DeliveryDate DATE, Status NVARCHAR(30), FOREIGN KEY (SalesOrderId) REFERENCES SalesOrders(Id));
CREATE TABLE Invoices (Id INT IDENTITY(1,1) PRIMARY KEY, SalesOrderId INT NOT NULL UNIQUE, InvoiceDate DATE NOT NULL, TotalAmount DECIMAL(18,2) NOT NULL, PaidAmount DECIMAL(18,2) NOT NULL DEFAULT 0, Status NVARCHAR(30) NOT NULL, FOREIGN KEY (SalesOrderId) REFERENCES SalesOrders(Id));
CREATE TABLE Payments (Id INT IDENTITY(1,1) PRIMARY KEY, InvoiceId INT NOT NULL, PaymentDate DATE NOT NULL, Amount DECIMAL(18,2) NOT NULL, PaymentMethod NVARCHAR(30) NOT NULL, FOREIGN KEY (InvoiceId) REFERENCES Invoices(Id));
