CREATE DATABASE InventoryDB;
GO
USE InventoryDB;
GO

CREATE TABLE Roles (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(50) UNIQUE NOT NULL);
CREATE TABLE Permissions (Id INT IDENTITY PRIMARY KEY, [Key] NVARCHAR(100) UNIQUE NOT NULL, Description NVARCHAR(255));
CREATE TABLE Users (
  Id INT IDENTITY PRIMARY KEY,
  FullName NVARCHAR(100) NOT NULL,
  Email NVARCHAR(120) UNIQUE NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  IsActive BIT DEFAULT 1,
  CreatedAt DATETIME2 DEFAULT SYSDATETIME()
);
CREATE TABLE UserRoles (UserId INT NOT NULL, RoleId INT NOT NULL, PRIMARY KEY(UserId, RoleId), FOREIGN KEY(UserId) REFERENCES Users(Id), FOREIGN KEY(RoleId) REFERENCES Roles(Id));
CREATE TABLE RolePermissions (RoleId INT NOT NULL, PermissionId INT NOT NULL, PRIMARY KEY(RoleId, PermissionId), FOREIGN KEY(RoleId) REFERENCES Roles(Id), FOREIGN KEY(PermissionId) REFERENCES Permissions(Id));

CREATE TABLE Categories (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL, Description NVARCHAR(255));
CREATE TABLE Suppliers (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL, Email NVARCHAR(120), Phone NVARCHAR(30), Address NVARCHAR(255));
CREATE TABLE Warehouses (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL, Location NVARCHAR(255), IsActive BIT DEFAULT 1);
CREATE TABLE Products (
  Id INT IDENTITY PRIMARY KEY,
  SKU NVARCHAR(40) UNIQUE NOT NULL,
  Name NVARCHAR(120) NOT NULL,
  CategoryId INT NOT NULL,
  SupplierId INT NULL,
  UnitPrice DECIMAL(18,2) NOT NULL,
  ReorderLevel INT DEFAULT 10,
  FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
  FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id)
);
CREATE TABLE Inventory (
  Id INT IDENTITY PRIMARY KEY,
  ProductId INT NOT NULL,
  WarehouseId INT NOT NULL,
  Quantity INT NOT NULL DEFAULT 0,
  UNIQUE(ProductId, WarehouseId),
  FOREIGN KEY(ProductId) REFERENCES Products(Id),
  FOREIGN KEY(WarehouseId) REFERENCES Warehouses(Id)
);
CREATE TABLE InventoryTransactions (
  Id INT IDENTITY PRIMARY KEY,
  ProductId INT NOT NULL,
  WarehouseId INT NOT NULL,
  QuantityChange INT NOT NULL,
  TransactionType NVARCHAR(30) NOT NULL,
  ReferenceType NVARCHAR(30),
  ReferenceId INT,
  CreatedAt DATETIME2 DEFAULT SYSDATETIME(),
  FOREIGN KEY(ProductId) REFERENCES Products(Id),
  FOREIGN KEY(WarehouseId) REFERENCES Warehouses(Id)
);

CREATE TABLE PurchaseOrders (Id INT IDENTITY PRIMARY KEY, SupplierId INT NOT NULL, OrderDate DATE NOT NULL, Status NVARCHAR(20) NOT NULL, WarehouseId INT NOT NULL, FOREIGN KEY(SupplierId) REFERENCES Suppliers(Id), FOREIGN KEY(WarehouseId) REFERENCES Warehouses(Id));
CREATE TABLE PurchaseOrderDetails (Id INT IDENTITY PRIMARY KEY, PurchaseOrderId INT NOT NULL, ProductId INT NOT NULL, Quantity INT NOT NULL, UnitCost DECIMAL(18,2) NOT NULL, FOREIGN KEY(PurchaseOrderId) REFERENCES PurchaseOrders(Id), FOREIGN KEY(ProductId) REFERENCES Products(Id));

CREATE TABLE Customers (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL, Email NVARCHAR(120), Phone NVARCHAR(30), Address NVARCHAR(255));
CREATE TABLE SalesOrders (Id INT IDENTITY PRIMARY KEY, CustomerId INT NOT NULL, OrderDate DATE NOT NULL, Status NVARCHAR(20) NOT NULL, WarehouseId INT NOT NULL, FOREIGN KEY(CustomerId) REFERENCES Customers(Id), FOREIGN KEY(WarehouseId) REFERENCES Warehouses(Id));
CREATE TABLE SalesOrderDetails (Id INT IDENTITY PRIMARY KEY, SalesOrderId INT NOT NULL, ProductId INT NOT NULL, Quantity INT NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL, FOREIGN KEY(SalesOrderId) REFERENCES SalesOrders(Id), FOREIGN KEY(ProductId) REFERENCES Products(Id));

CREATE TABLE Deliveries (Id INT IDENTITY PRIMARY KEY, SalesOrderId INT NOT NULL, DeliveredDate DATE, Status NVARCHAR(20) NOT NULL, TrackingNo NVARCHAR(80), FOREIGN KEY(SalesOrderId) REFERENCES SalesOrders(Id));
CREATE TABLE Invoices (Id INT IDENTITY PRIMARY KEY, SalesOrderId INT UNIQUE NOT NULL, InvoiceNumber NVARCHAR(50) UNIQUE NOT NULL, InvoiceDate DATE NOT NULL, TotalAmount DECIMAL(18,2) NOT NULL, PaidAmount DECIMAL(18,2) DEFAULT 0, Status NVARCHAR(20) NOT NULL, FOREIGN KEY(SalesOrderId) REFERENCES SalesOrders(Id));
CREATE TABLE Payments (Id INT IDENTITY PRIMARY KEY, InvoiceId INT NOT NULL, Amount DECIMAL(18,2) NOT NULL, PaymentDate DATE NOT NULL, Method NVARCHAR(30) NOT NULL, ReferenceNo NVARCHAR(80), FOREIGN KEY(InvoiceId) REFERENCES Invoices(Id));
GO
